# Generated by Django 5.0.3 on 2024-04-09 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(db_index=True, max_length=100, verbose_name='Category')),
                ('cat_name_ru', models.CharField(db_index=True, max_length=100, null=True, verbose_name='Category')),
                ('cat_name_en', models.CharField(db_index=True, max_length=100, null=True, verbose_name='Category')),
                ('cat_slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255, verbose_name='Header')),
                ('header_ru', models.CharField(max_length=255, null=True, verbose_name='Header')),
                ('header_en', models.CharField(max_length=255, null=True, verbose_name='Header')),
                ('post', models.TextField(blank=True, verbose_name='Content')),
                ('post_ru', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('post_en', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Time of change')),
                ('is_published', models.BooleanField(default=True, verbose_name='Status')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content', to='base.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'object',
                'verbose_name_plural': 'Objects',
            },
        ),
    ]
